web/router.ex
defmodule Codecasts.Router do
  use Codecasts.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :require_login do
    plug Guardian.Plug.EnsureAuthenticated, handler: Codecasts.AuthErrorHandler
    plug Codecasts.Plug.CurrentUser
  end

  scope "/", Codecasts do
    pipe_through [:browser, :browser_session, :require_login]

    get "/profile", UserController, :edit
    put "/profile", UserController, :update

    resources "/events", EventController
    
    get "/", PageController, :index
  end

  scope "/sessions", Codecasts do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/login", SessionController, :login
    get "/logout", SessionController, :logout

    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :callback

  end

  # Other scopes may use custom stacks.
  # scope "/api", Codecasts do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Codecasts.LayoutView do
  use Codecasts.Web, :view
  import Phoenix.Controller, only: [get_flash: 1]

  # Function to show flash messages using bootstrap classes
  def show_flash(conn) do
    get_flash(conn) |> flash_msg
  end

  def flash_msg(%{"info" => msg}) do
    ~E"<div class='alert alert-info'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= msg %></div>"
  end

  def flash_msg(%{"error" => msg}) do
    ~E"<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= msg %></div>"
  end

  def flash_msg(_) do
    nil
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CodeCasts<%= if (assigns[:page_title]) do " - " + @title; end %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link gettext("CodeCasts"), to: page_path(@conn, :index), class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% controller =  @conn.private.phoenix_controller %>
            <li <%= if (controller == Codecasts.PageController) do 'class=active' end %>>
              <%= link gettext("Start"), to: page_path(@conn, :index) %>
            </li>
            <li <%= if (controller == Codecasts.EventController) do 'class=active' end %>>
              <%= link gettext("Events"), to: event_path(@conn, :index) %>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li>
              <p class="navbar-btn">
                <%= link gettext("Add new event"), to: event_path(@conn, :new), class: "btn btn-primary" %>
              </p>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link gettext("Edit my profile"), to: user_path(@conn, :edit) %></li>
                <li><%= link gettext("Logout"), to: session_path(@conn, :logout) %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <%= show_flash @conn %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CodeCasts<%= if (assigns[:page_title]) do " - " + @title; end %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/session.css") %>">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container session-container">

      <%= show_flash @conn %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Codecasts</h3>
        </div>
        <div class="panel-body">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>